version: 0.0
os: linux
files:
  - source: /  # This refers to everything in the root of your repository
    destination: /home/ec2-user/my-flask-app  # Directory on EC2 where the files will be copied

hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 180
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 180
